### PR TITLE
#130 Verify no instance exists before uninstalling an extension

### LINKED ISSUE #130: Verify that there are no instances left when uninstalling an extension
When you try to uninstall an extension while there still exists an instance this may fail. For virtual schemas the request will fail with status 500 internal server error. The following will be printed in the log:

>failed to uninstall extension "s3-vs-extension.js": error executing statement "DROP ADAPTER SCRIPT \"EXA_EXTENSIONS\".\"S3_FILES_ADAPTER\"": E-EGOD-11: execution failed with SQL error code '42500' and message 'At least one virtual schema existing for this Adapter Script, please drop all Virtual Schemas of this Adapter first. (Session: 1775811000426561536)

To improve usability the EM must return `412 Precondition Failed` with a helpful error message in this case.

### Note
We could implement this in the extension and check for instances before. But this would mean code duplication across all extensions. That's why we need to implement this centrally in EM.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #130

### CODE REVIEW

File: pkg/extensionController/controller.go [hunk 1]
```diff
@@ -209,7 +209,15 @@ func (c *controllerImpl) UninstallExtension(txCtx *transaction.TransactionContex
...
+	extensionCtx := c.createExtensionContext(txCtx)
+	instances, err := extension.ListInstances(extensionCtx, extensionVersion)
+	if err != nil {
+		return fmt.Errorf("failed to check existing instances: %w", err)
+	}
+	if len(instances) > 0 {
+		return fmt.Errorf("cannot uninstall extension because %d instance(s) still exist", len(instances))
+	}
+	return extension.Uninstall(extensionCtx, extensionVersion)
 }
```
Comment (ckunki) [inline pkg/extensionController/controller.go:222]: Only one questions: Who will receive this error in which situation?
Will it be an interactive (GUI) user seeing this error message?
Is there a mitigation EM could propose to the user? 
And does the user know what an "instance" is?

**Review by ckunki — CHANGES_REQUESTED** [review]

File: pkg/extensionController/controller.go (hunk 1 above)
Comment (kaklakariada) [reply pkg/extensionController/controller.go:222]: Good point. Currently this would result in an internal server error (500). I should change this to a 400 status.
Actually the UI should not allow uninstalling as long as instances exist. So this is just additional safety.

**Review by ckunki — DISMISSED** [review]

**Review by ckunki — APPROVED** [review]

**Review by ckunki — APPROVED** [review]
